import streamlit as st
import sys
import os

# Add parent dir to path so we can import 'agent'
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from agent.core import PharmaAgent
import importlib
import agent.core

# Force reload of core module to pick up changes
importlib.reload(agent.core)
from agent.core import PharmaAgent

st.set_page_config(page_title="Pharma Discovery Agent", page_icon="🧬", layout="wide")

st.title("🧬 Pharma Discovery Research Agent")
st.markdown("""
**Expert AI Assistant for Clinical Trial & Literature Analysis**
*Sources: ClinicalTrials.gov, PubMed, NEJM (Last 10 Years)*
""")

st.markdown("""
<style>
    /* Card Container Style */
    .study-card {
        background-color: #262730;
        padding: 20px;
        border-radius: 10px;
        margin-bottom: 20px;
        border: 1px solid #484b55;
        transition: transform 0.2s ease, box-shadow 0.2s ease;
    }
    .study-card:hover {
        transform: translateY(-5px);
        box-shadow: 0 5px 15px rgba(0,0,0,0.3);
        border-color: #ff4b4b;
    }
    
    /* Fade In Animation */
    @keyframes fadeIn {
        from { opacity: 0; transform: translateY(10px); }
        to { opacity: 1; transform: translateY(0); }
    }
    .fade-in {
        animation: fadeIn 0.5s ease-out forwards;
    }
</style>
""", unsafe_allow_html=True)

# Initialize Agent
@st.cache_resource
def get_agent_chat_kv6():
    try:
        importlib.reload(agent.core) # Double check reload here
        from agent.core import PharmaAgent
        return PharmaAgent()
    except Exception as e:
        st.error(f"Failed to initialize agent: {e}")
        return None

agent = get_agent_chat_kv6()

# --- Session State Management ---
if 'studies' not in st.session_state:
    st.session_state.studies = [] 
if 'results_html' not in st.session_state:
    st.session_state.results_html = ""
if 'chat_message_history' not in st.session_state: 
    st.session_state.chat_message_history = [] 

query = st.text_input("Enter your research question (e.g., 'NSCLC KRAS G12C inhibitors biomarkers'):")
search_button = st.button("Search & Analyze")

if search_button and query:
    if not agent:
        st.error("Agent not initialized. Check API keys.")
    else:
        # Reset Chat on new search
        st.session_state.chat_message_history = []
        
        # Progress Bar and Status Container
        progress_bar = st.progress(0)
        status_text = st.empty()
        
        try:
            status_text.text("Searching databases (ClinicalTrials.gov, PubMed, NEJM)...")
            progress_bar.progress(20)
            
            # Get Results (List[Study])
            results_list = agent.search_and_analyze(query)
            st.session_state.studies = results_list
            
            progress_bar.progress(80)
            status_text.text("Finalizing analysis and formatting...")
            
            # Format results as string to match LEGACY look
            # The agent method no longer returns string, so we format here
            formatted_parts = []
            for study in results_list:
                formatted_parts.append(agent.formatter.format_study(study))
                formatted_parts.append("---")
            
            results_str = "\n\n".join(formatted_parts)
            
            # Save for display
            if not results_list: 
                results_str = "No relevant records found in ClinicalTrials.gov / AACT / PubMed / NEJM within the specified timeframe.\n\nTry refining your search terms."

            st.session_state.results_html = f'<div class="fade-in">{results_str}</div>'
            
            progress_bar.progress(100)
            status_text.empty()
            progress_bar.empty()
            
        except Exception as e:
            st.error(f"An error occurred during analysis: {e}")
            st.session_state.studies = []

# --- Persistent Display of Results ---
if st.session_state.results_html:
    st.markdown("### Research Results")
    st.markdown(st.session_state.results_html, unsafe_allow_html=True)
            
st.markdown("---")
st.caption("Generated by Pharma Discovery Agent | Reference Score: 0-100 based on biomarker/AE relevance.")


# --- CHAT INTERFACE (Added at bottom) ---
if st.session_state.studies:
    st.markdown("### 💬 Chat with these Results")
    st.caption("Ask questions about the studies found above.")
    
    # Display Chat History
    for message in st.session_state.chat_message_history:
        with st.chat_message(message["role"]):
            st.markdown(message["content"])

    # Chat Input
    if prompt := st.chat_input("Ask a follow-up question..."):
        # Add User Message
        st.session_state.chat_message_history.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.markdown(prompt)
            
        # Get Bot Response
        with st.chat_message("assistant"):
            with st.spinner("Analyzing studies..."):
                response = agent.answer_question(st.session_state.studies, prompt)
                st.markdown(response)
        
        # Add Bot Response
        st.session_state.chat_message_history.append({"role": "assistant", "content": response})
