import streamlit as st
import sys
import os

# Add parent dir to path so we can import 'agent'
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from agent.core import PharmaAgent

st.set_page_config(page_title="Pharma Discovery Agent", page_icon="🧬", layout="wide")

st.title("🧬 Pharma Discovery Research Agent")
st.markdown("""
**Expert AI Assistant for Clinical Trial & Literature Analysis**
*Sources: ClinicalTrials.gov, PubMed, NEJM (Last 10 Years)*
""")

st.markdown("""
<style>
    /* Card Container Style */
    .study-card {
        background-color: #262730;
        padding: 20px;
        border-radius: 10px;
        margin-bottom: 20px;
        border: 1px solid #484b55;
        transition: transform 0.2s ease, box-shadow 0.2s ease;
    }
    .study-card:hover {
        transform: translateY(-5px);
        box-shadow: 0 5px 15px rgba(0,0,0,0.3);
        border-color: #ff4b4b;
    }
    
    /* Fade In Animation */
    @keyframes fadeIn {
        from { opacity: 0; transform: translateY(10px); }
        to { opacity: 1; transform: translateY(0); }
    }
    .fade-in {
        animation: fadeIn 0.5s ease-out forwards;
    }
</style>
""", unsafe_allow_html=True)

# Initialize Agent
@st.cache_resource
def get_agent_reverted():
    try:
        return PharmaAgent()
    except Exception as e:
        st.error(f"Failed to initialize agent: {e}")
        return None

agent = get_agent_reverted()

query = st.text_input("Enter your research question (e.g., 'NSCLC KRAS G12C inhibitors biomarkers'):")
search_button = st.button("Search & Analyze")

if search_button and query:
    if not agent:
        st.error("Agent not initialized. Check API keys.")
    else:
        # Progress Bar and Status Container
        progress_bar = st.progress(0)
        status_text = st.empty()
        
        try:
            status_text.text("Searching databases (ClinicalTrials.gov, PubMed, NEJM)...")
            progress_bar.progress(20)
            
            # Note: Tying progress bar strictly to agent internal progress is hard without callbacks.
            # We'll simulate milestones or refactor agent later. For now, simple steps.
            
            # Ideally, agent.search_and_analyze would yield progress updates.
            # Since it returns a string, we wrap it.
            
            results = agent.search_and_analyze(query)
            
            progress_bar.progress(80)
            status_text.text("Finalizing analysis and formatting...")
            
            progress_bar.progress(100)
            status_text.empty()
            progress_bar.empty()
            
            st.markdown("### Research Results")
            
            # Wrap results in a container for animation class (if we parsed them individually, we could apply classes)
            # Since 'results' is a markdown string, we can't easily wrap individual cards with Python logic here 
            # without changing the agent to return objects. 
            
            # HACK: Post-process the markdown string to wrap "---" separated blocks in HTML divs?
            # Or just wrap the whole thing.
            
            # Better approach for animations: 
            # Let's simple wrap the whole output in a fade-in div.
            st.markdown(f'<div class="fade-in">{results}</div>', unsafe_allow_html=True)
            
        except Exception as e:
            st.error(f"An error occurred during analysis: {e}")

st.markdown("---")
st.caption("Generated by Pharma Discovery Agent | Reference Score: 0-100 based on biomarker/AE relevance.")
